sudo: required
dist: trusty

language: haxe

haxe:
  - "3.2.1"
  - development
  
matrix:
  allow_failures:
    - haxe: development
    
install:
  - haxelib install tink_runloop
  - haxelib install travix
  - haxelib run travix install

script:
  - haxelib run travix node
  - haxelib run travix neko
  - haxelib run travix neko -lib tink_runloop
  - haxelib run travix java
  - haxelib run travix java -lib tink_runloop
  - haxelib run travix cpp
  - haxelib run travix cpp -lib tink_runloop
